version: '3.8'

services:
  inference-server:
    image: tfunes/inference-server:latest
    container_name: inference-server
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
    restart: unless-stopped