[agent]
  interval = "10s"
  round_interval = true
  hostname = "api-detection-local"
  metric_buffer_limit = 10000
  flush_interval = "10s"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "${INFLUXDB_TOKEN}"
  organization = "${INFLUXDB_ORG}"
  bucket = "${INFLUXDB_BUCKET}"
  timeout = "5s"

[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false

[[inputs.mem]]

[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]

[[inputs.diskio]]

[[inputs.net]]

[[inputs.system]]

[[inputs.processes]]

[[inputs.prometheus]]
  urls = ["http://api:8000/metrics"]
  metric_version = 2

[[inputs.http_response]]
  urls = ["http://api:8000/health"]
  method = "GET"
  response_timeout = "5s"

[[inputs.http_response]]
  urls = ["http://inference-server:8000/health"]
  method = "GET"
  response_timeout = "5s"
  name_override = "inference_health"

[[processors.enum]]
  namepass = ["http_response", "inference_health"]

  [[processors.enum.mapping]]
    fields = ["result_type"]
    dest = "estado_binario"
    default = 0

    [processors.enum.mapping.value_mappings]
      success = 1
