apiVersion: 1
datasources:
  - name: InfluxDB_SOA
    type: influxdb
    uid: bfhay1m297a4gf
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: soa
      defaultBucket: metrics
    secureJsonData:
      token: ${INFLUXDB_TOKEN}
    editable: true
